[versions]
# Plugins
agp = "9.0.1"

junit4 = "4.13.2"
junit5 = "6.0.3"
robolectric = "4.16.1"
androidDesugarJdkLibs = "2.1.5"

detektPlugin = "1.23.8"
ktlintPlugin = "14.0.1"

kotlinVersion = "2.3.10"
kotlin-ksp = "2.3.5"
kotlinCoroutinesVersion = "1.10.2"

dokkaVersion = "2.1.0"
maven-publish = "0.36.0"

# AndroidX
annotation = "1.9.1"
coreKtx = "1.17.0"
activityKtx = "1.12.4"
fragmentKtx = "1.8.9"
livedata-core = "2.10.0"

# Google
gms-play-auth = "18.3.0"

# Test
androidx-test-ext = "1.2.1"
androidx-test-arch = "2.2.0"
androidx-test-core = "1.6.1"
androidx-test-runner = "1.6.2"
mockk = "1.13.16"

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinVersion" }

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinVersion" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }
google-ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "kotlin-ksp" }
kotlin-parcelize-gradlePlugin = { group = "org.jetbrains.kotlin.plugin.parcelize", name = "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin", version.ref = "kotlinVersion" }

publish-gradlePlugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }

kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutinesVersion" }

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }

livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "livedata-core" }

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }

dokka-java = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokkaVersion" }

# Google GSM
gms-play-auth = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "gms-play-auth" }


# Test
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-arch = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidx-test-arch" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
jupiter-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[bundles]
androidX = [
    "coreKtx",
    "activityKtx",
    "fragmentKtx"
]

kotlin = [
    "kotlin-stdlib",
]

test-unit = [
    "jupiter",
    "jupiter-api",
]

test-android-unit = [
    "junit4",
    "mockk",
    "robolectric",
    "jupiter-api",
    "androidx-test-core",
    "androidx-test-arch",
]

test-android = [
    "androidx-test-runner",
    "androidx-test-arch",
    "androidx-test-core",
    "androidx-test-ext",
    "jupiter-api",
]